export const LANGUAGE_CN = {
  name: '名称',
  phone: '电话',
  title: '标题',
  address: '地址',
  fax: '传真',
  short_title: '副标题',
  tag: '标签',
  tags: '标签',
  language: '语言',
  content_type: '文档类型',
  order: '排序',
  description: '描述',
  path: '路径',
  content: '内容',
  poster: '海报',
  article: '文档',
  thumb: '缩略图',
  keywords: '标签',
  menu: '菜单',
  menus: '菜单',
  body: '文档内容',
  template: '模板',
  show: '显示',
  channel: '频道',
  dashboard: '工作台',
  actions: '操作',
  add: '添加',
  delete: '删除',
  edit: '编辑',
  save: '保存',
  Logout: '退出',
  icp: '备案号',
  wechat: '微信号',
  business_scope: '经营范围',
  url: '网址',
  code_public: '公众号',
  code_mini: '小程序',
  code_download: '下载',
  none: '无',
  custom_type: '自定义类型',
  confirm: '确定',
  cancel: '取消',
  dialog_msg: '您确定要删除该条信息吗？',
  'AiFox CMS Manage': '智狐CMS管理平台',
  'Add Submenu': '添加子栏目',
  'Add Article': '添加文档',
  'View Articles': '查看文档',
  'Content Manage': '内容管理',
  'System Manage': '系统管理',
  'Menu Manage': '栏目管理',
  'Article Manage': '文档管理',
  'Address Manage': '地址管理',
  'ContentType Manage': '文档类型',
  'File Manage': '文件管理',
  'Site Manage': '站点设置',
  'Default Language': '默认语言',
  'User Info': '用户信息',
  'User Manage': '用户管理',
  file: '文件',
  missing: '缺少',
  back: '返回',
  search: '搜索',
  company: '公司',
  username: '用户名',
  email: '邮箱',
  password: '密码',
  role: '角色',
  confirmed: '启用',
  true: '是',
  false: '否',
  'Identifier or password invalid.': '用户名或密码错误'
};
